---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springdemoapp
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/rajshivaram/argocd-app-config.git
    targetRevision: HEAD
    path: dev/app/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true
    hooks:
      - name: wait-for-database
        sync:
          timeout: 600s
        after:
          - source:
              repoURL: https://github.com/rajshivaram/argocd-app-config.git
              targetRevision: HEAD
              path: dev/db/
            destination:
              server: https://kubernetes.default.svc
              namespace: default
